services: 
  mongo: 
    container_name: mongo
    image: "mongo:3.6"
    volumes:
      - "./data/configdb:/data/configdb"
      - "./data/db:/data/db"
    ports: 
      - "27017:27017"
networks: 
  yapi:
